version: 2.1

jobs:
  dockerize:
    docker:
      - image: docker:24
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker image build --tag "acmeorg/foobar:${CIRCLE_SHA1}" -f Dockerfile .
      - run:
          name: Save docker image as tar
          command: |
            mkdir -p images
            docker image save -o "images/acmeorg_foobar_${CIRCLE_SHA1}" "acmeorg/foobar:${CIRCLE_SHA1}"
      - persist_to_workspace:
          root: .
          paths:
            - images

  build:
    docker:
      - image: docker:24
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
      - run:
          name: Load image
          command: |
            docker image load < "images/acmeorg_foobar_${CIRCLE_SHA1}"
      - run:
          name: Build Autosar App
          command: |
            docker run acmeorg/foobar:${CIRCLE_SHA1} make autosar

workflows:
  scheduled-build:
    jobs:
      - dockerize:
          filters:
            branches:
              only: master
      - build:
          requires:
            - dockerize
          filters:
            branches:
              only: master