name: Scheduled Build

on:
  push:
    branches:
      - master

jobs:
  dockerize:
    runs-on: ubuntu-latest
    container:
      image: docker:19.03.12
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        run: |
          docker build --tag "acmeorg/foobar:${{ github.sha }}" -f Dockerfile .
      - name: Save Docker image as tar
        run: |
          mkdir -p images
          docker image save -o "images/acmeorg_foobar_${{ github.sha }}" "acmeorg/foobar:${{ github.sha }}"
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: images
          path: images

  build:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: images
          path: images
      - name: Load Docker image
        run: |
          docker load < "images/acmeorg_foobar_${{ github.sha }}"
      - name: Build Autosar App
        run: |
          docker run acmeorg/foobar:${{ github.sha }} make autosar
